networks:
  credentials_network:
    driver: bridge
    ipam:
      config:
        - subnet: "169.254.170.0/24"

services:
  ecs-local-endpoints:
    image: amazon/amazon-ecs-local-container-endpoints
    volumes:
      - /var/run:/var/run
      - /c/Users/user/.aws:/home/.aws:ro
    environment:
      AWS_PROFILE: "ilmn25"
    networks:
      credentials_network:
        ipv4_address: 169.254.170.2

  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - ecs-local-endpoints
    networks:
      credentials_network:
        ipv4_address: 169.254.170.3
    environment:
      AWS_DEFAULT_REGION: "ap-southeast-2"
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: "/creds"
      ECS_CONTAINER_METADATA_URI_V4: "http://169.254.170.2/v4"
